name: advanced_share
description: Flutter plugin for sharing content and file via native ui for Android 
version: 0.1.0
author: Mertcan Dinler <mertdinlerin@gmail.com>
homepage: https://github.com/mrtcndnlr/Flutter-Advanced-Share

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: in.mertcan.advancedshare
    pluginClass: AdvancedSharePlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"